import { fileURLToPath } from "node:url";

import { defineConfig } from "vitest/config";

const srcRoot = fileURLToPath(new URL("./src/", import.meta.url));

export default defineConfig({
  resolve: { alias: [{ find: /^#(.+\.ts)$/, replacement: `${srcRoot}$1` }] },
  test: {
    include: [
      "src/**/*.{test,spec}.ts",
      "src/**/*.{test,spec}.tsx",
      "tests/**/*.{test,spec}.ts",
    ],
    exclude: ["sample/**/*.test.ts", "sample/**/*.test.tsx"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: [
        "bin/**",
        "coverage/**",
        "dist/**",
        "hooks/**",
        "node_modules/**",
        "sample/**",
        "**/.*/**",
        "**/.*",
        "src/**/tests/**",
        "src/tests/**",
        "tests/**",
        "**/*.test.ts",
        "**/*.test.tsx",
        "*.config.*",
        "scripts/run-tests.cjs",
        "src/constant.ts",
        "src/types.ts",
        "src/utils.ts",
        "src/**/types.ts",
        "src/analyzer/constant.ts",
        "src/analyzer/utils.ts",
        "src/analyzer/mocks/constant.ts",
        "src/analyzer/mocks/utils.ts",
        "src/analyzer/visual/constant.ts",
        "src/analyzer/visual/utils.ts",
        "src/cli/constant.ts",
        "src/cli/utils.ts",
        "src/cli/commands/constant.ts",
        "src/cli/commands/utils.ts",
        "src/generator/constant.ts",
        "src/generator/utils.ts",
        "src/generator/mocks/constant.ts",
        "src/generator/mocks/utils.ts",
        "src/generator/transforms/constant.ts",
        "src/generator/transforms/utils.ts",
        "src/install/constant.ts",
        "src/install/utils.ts",
        "src/install/runtimes/constant.ts",
        "src/install/runtimes/utils.ts",
        "src/learner/constant.ts",
        "src/learner/utils.ts",
        "src/parser/constant.ts",
        "src/parser/utils.ts",
        "src/parser/steps/constant.ts",
        "src/parser/steps/utils.ts",
        "src/scorer/constant.ts",
        "src/scorer/utils.ts",
        "src/templates/constant.ts",
        "src/templates/utils.ts",
        "src/types/constant.ts",
        "src/types/utils.ts",
      ],
    },
  },
});
