import type { RuntimeDefinition, RuntimeTarget } from "#install/types.ts";

export const RUNTIME_REGISTRY: Record<RuntimeTarget, RuntimeDefinition> = {
  claude: {
    id: "claude",
    displayName: "Claude Code",
    family: "prompt",
    globalDirectorySegments: [".claude"],
    localDirectoryName: ".claude",
    packageContainerSegments: ["commands", "@tr-rtl", "cli"],
    verificationCommand: "/@tr-rtl/cli:help",
    ownershipMarkerFileName: "install-manifest.json",
    assets: [],
  },
  opencode: {
    id: "opencode",
    displayName: "OpenCode",
    family: "prompt",
    globalDirectorySegments: [".config", "opencode"],
    localDirectoryName: ".opencode",
    packageContainerSegments: ["commands", "@tr-rtl", "cli"],
    verificationCommand: "/@tr-rtl/cli-help",
    ownershipMarkerFileName: "install-manifest.json",
    assets: [],
  },
  gemini: {
    id: "gemini",
    displayName: "Gemini CLI",
    family: "prompt",
    globalDirectorySegments: [".gemini"],
    localDirectoryName: ".gemini",
    packageContainerSegments: ["commands", "@tr-rtl", "cli"],
    verificationCommand: "/@tr-rtl/cli:help",
    ownershipMarkerFileName: "install-manifest.json",
    assets: [],
  },
  codex: {
    id: "codex",
    displayName: "Codex",
    family: "skill",
    globalDirectorySegments: [".codex"],
    localDirectoryName: ".codex",
    packageContainerSegments: ["skills"],
    verificationCommand: "$@tr-rtl/cli-help",
    ownershipMarkerFileName: "@tr-rtl-manifest.json",
    assets: [],
  },
};
